# Main Credits :- @StarkxD 
# Partial Credit :- @PureindiaLover

from telethon import events
import random, re
from userbot.utils import admin_cmd
import asyncio

global USER # pylint:disable=E0602 
global REASON



@borg.on(admin_cmd("fban ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    global USER # pylint:disable=E0602
    global REASON
    USER = event.pattern_match.group(2)
    REASON = event.pattern_match.group(2)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5e9e0a69-15cb-4998-bbd0-4e782ba8b649 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b21e23eb-1ce4-4782-84c5-315e13d9054d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 2f1b0e29-ec31-4828-afb0-58ec2a502b04 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f7521eba-3ad2-483f-9de0-aa34cea6f20b ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 0e32f678-9c5f-47d5-b512-a3a607f1fd99 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a51de70b-db1b-41f9-ab5d-3893379df31d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f0f125a4-9927-4f22-a40e-0f010ef0c45e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 826f1a3f-a1b3-4012-a5d0-28669fbb3020 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 1e1595b9-7185-4646-b024-4b6fb54a237d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 94259446-b741-4ae5-ac99-16e00dd24e4a ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed fc7d5b2b-fbde-47ad-b11a-8d6edaaeb69f ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 19df4d28-aebc-423a-9a45-2e6ca3e6b122 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 7389172d-b5ad-42bb-80af-5d0b50605390 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a4bcd10a-8f14-4bf3-9226-13fb873a0316 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 429df5fb-dd75-4e10-844b-03639e56208c ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 45dc0011-bfab-4473-80b6-196116fd70d0 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 60dc4819-1bea-4084-9953-6c3b3110e851 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ae1459de-b563-4818-a8f1-a0454bbb8abd ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed aa3ac063-686d-41d8-91a0-0e3acdbe2560 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 392a29a1-74c8-4d03-8a58-4cb25db7732e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 45105c24-6626-41c2-8f16-516de3c12322 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5fae7757-4e53-4d31-bda4-94c1d64d3d73 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 660722c2-145b-4c36-9ef1-60537b37fec4 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed cacef97d-b4a7-4e64-b042-8f8a873976c4 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5b4341a4-891a-407e-9437-261bfc7ed3da ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 4020046f-d12c-452f-8ed6-b5058a895647 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed c5ddfe94-812a-4c4f-958d-af64428de336 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 1fbabe40-63bf-45f5-98e5-629be40be29d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 4762dde6-8caa-490e-a451-c27991dbac43 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 22e687be-23d9-49f0-be3c-d3a93ec91d36 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b43333bf-71b3-4206-a855-98dce03aa93e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f9dd42bf-8314-49e4-ae9e-e2469de033c5 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b13f7555-16bb-457d-93fe-0400b7b3ff97 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed e03fd554-9361-476f-8c4a-aa8fc4e09f11 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 83d0475a-087b-4292-8589-a905f607c35b ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ec9f1647-822f-4003-a423-788b77612060 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 4601d3d4-3de9-48c0-8149-3708f8e3897b ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 42989760-b3eb-4f0a-bb22-9f87a6d7169e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 58ade60f-7e1a-4d0a-8320-17cd6e0bbe70 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {USER} {REASON}")
        await asyncio.sleep(50)


# Unfban Plug-in 

@borg.on(admin_cmd("unfban ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    global USER # pylint:disable=E0602
    global REASON
    USER = event.pattern_match.group(1)
    REASON = event.pattern_match.group(1)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5e9e0a69-15cb-4998-bbd0-4e782ba8b649 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b21e23eb-1ce4-4782-84c5-315e13d9054d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 2f1b0e29-ec31-4828-afb0-58ec2a502b04 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f7521eba-3ad2-483f-9de0-aa34cea6f20b ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 0e32f678-9c5f-47d5-b512-a3a607f1fd99 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a51de70b-db1b-41f9-ab5d-3893379df31d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f0f125a4-9927-4f22-a40e-0f010ef0c45e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 826f1a3f-a1b3-4012-a5d0-28669fbb3020 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 1e1595b9-7185-4646-b024-4b6fb54a237d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 94259446-b741-4ae5-ac99-16e00dd24e4a ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed fc7d5b2b-fbde-47ad-b11a-8d6edaaeb69f ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 19df4d28-aebc-423a-9a45-2e6ca3e6b122 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 7389172d-b5ad-42bb-80af-5d0b50605390 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a4bcd10a-8f14-4bf3-9226-13fb873a0316 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 429df5fb-dd75-4e10-844b-03639e56208c ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 45dc0011-bfab-4473-80b6-196116fd70d0 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 60dc4819-1bea-4084-9953-6c3b3110e851 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ae1459de-b563-4818-a8f1-a0454bbb8abd ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed aa3ac063-686d-41d8-91a0-0e3acdbe2560 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 392a29a1-74c8-4d03-8a58-4cb25db7732e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 45105c24-6626-41c2-8f16-516de3c12322 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5fae7757-4e53-4d31-bda4-94c1d64d3d73 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 660722c2-145b-4c36-9ef1-60537b37fec4 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed cacef97d-b4a7-4e64-b042-8f8a873976c4 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5b4341a4-891a-407e-9437-261bfc7ed3da ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 4020046f-d12c-452f-8ed6-b5058a895647 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed c5ddfe94-812a-4c4f-958d-af64428de336 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 1fbabe40-63bf-45f5-98e5-629be40be29d ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 4762dde6-8caa-490e-a451-c27991dbac43 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 22e687be-23d9-49f0-be3c-d3a93ec91d36 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b43333bf-71b3-4206-a855-98dce03aa93e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f9dd42bf-8314-49e4-ae9e-e2469de033c5 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b13f7555-16bb-457d-93fe-0400b7b3ff97 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed e03fd554-9361-476f-8c4a-aa8fc4e09f11 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 83d0475a-087b-4292-8589-a905f607c35b ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ec9f1647-822f-4003-a423-788b77612060 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 4601d3d4-3de9-48c0-8149-3708f8e3897b ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 58ade60f-7e1a-4d0a-8320-17cd6e0bbe70 ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 42989760-b3eb-4f0a-bb22-9f87a6d7169e ")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {USER} {REASON}")
        await asyncio.sleep(50)

